name: Build

on:
  push:
    branches-ignore:
      - master

jobs:

  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Utilities
      run: |
        brew install automake
        brew install libtool
        brew install libtiff
    - name: Install
      run: pod install
    - name: Build
      run: xcodebuild build-for-testing -workspace proj-libtiff-ios.xcworkspace -scheme proj-libtiff-ios -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14'
